# Generated by Django 4.1.7 on 2023-09-16 05:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SpinRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('last_step', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=11, message='last_step не должен быть больше 11.'), django.core.validators.MinValueValidator(limit_value=1, message='last_step не должен быть меньше 0.')])),
                ('rest_values', models.CharField(default='1,2,3,4,5,6,7,8,9,10', max_length=35)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='roulette_app.user')),
            ],
            options={
                'unique_together': {('round', 'last_step')},
            },
        ),
    ]
