# Generated by Django 4.1.7 on 2023-09-13 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinround',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spinround',
            name='last_step',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=11), django.core.validators.MinValueValidator(limit_value=0, message='last_step не должен быть меньше 0.')]),
        ),
        migrations.AlterUniqueTogether(
            name='spinround',
            unique_together={('round', 'last_step')},
        ),
    ]
