# Generated by Django 4.1.7 on 2023-09-13 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0002_spinround_round_alter_spinround_last_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinround',
            name='rest_values',
            field=models.CharField(default='[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]', max_length=30),
        ),
        migrations.AlterField(
            model_name='spinround',
            name='last_step',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=11, message='last_step не должен быть больше 11.'), django.core.validators.MinValueValidator(limit_value=0, message='last_step не должен быть меньше 0.')]),
        ),
    ]
