# Generated by Django 4.1.7 on 2023-09-13 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0003_spinround_rest_values_alter_spinround_last_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinround',
            name='last_step',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=11, message='last_step не должен быть больше 11.'), django.core.validators.MinValueValidator(limit_value=0, message='last_step не должен быть меньше 0.')]),
        ),
    ]
