# Generated by Django 4.1.7 on 2023-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0005_alter_spinround_last_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinround',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
