# Generated by Django 4.1.7 on 2023-09-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0006_alter_spinround_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinround',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spinround',
            name='rest_values',
            field=models.CharField(default='1,2,3,4,5,6,7,8,9,10', max_length=35),
        ),
    ]
