# Generated by Django 4.1.7 on 2023-09-15 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0007_spinround_finished_alter_spinround_rest_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinround',
            name='last_step',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=11, message='last_step не должен быть больше 11.'), django.core.validators.MinValueValidator(limit_value=0, message='last_step не должен быть меньше 0.')]),
        ),
    ]
